import React, { useState, useEffect } from 'react';
import ReactMarkdown from 'react-markdown';
import { Save, Loader2, AlertCircle, Check, Edit2, Edit3, X, FileText, BrainCircuit, Calendar, User, ShieldCheck, Target, TrendingUp, DollarSign, Scale, Printer, Download, Info } from 'lucide-react';
import { IPSDocument, TargetAllocation, Client } from '../types';
import { toPng } from 'html-to-image';
import jsPDF from 'jspdf';

/**
 * Props for the IPSEditor component.
 */
interface IPSEditorProps {
  /** The IPS document to edit or view, including its target allocations. */
  ips: IPSDocument & { target_allocations: TargetAllocation[] };
  /** The client associated with the IPS. */
  client: Client;
  /** Callback function to save the updated IPS. */
  onSave: (updatedIps: any) => Promise<void>;
  /** The role of the user viewing the IPS (advisor or client). Defaults to 'advisor'. */
  viewerRole?: 'advisor' | 'client';
  /** Callback function when the client accepts the IPS. */
  onAccept?: () => Promise<void>;
  /** Callback function to regenerate the IPS using AI. */
  onRegenerate?: () => Promise<void>;
  /** Optional array of previous IPS versions. */
  ipsVersions?: (IPSDocument & { target_allocations: TargetAllocation[] })[];
  /** Callback function when a different version of the IPS is selected. */
  onVersionSelect?: (versionId: string) => void;
  /** Callback function to delete the IPS. */
  onDelete?: () => Promise<void>;
  /** Whether the IPS is currently being generated by AI. */
  generatingIPS?: boolean;
}

/**
 * IPSEditor component provides an interface for viewing and editing Investment Policy Statements (IPS).
 * It allows advisors to modify various parameters of the IPS and clients to review and accept it.
 * It also supports versioning, PDF export, and AI-driven regeneration.
 * 
 * @param props - The component props.
 * @returns A JSX element representing the IPS editor.
 */
export default function IPSEditor({ ips, client, onSave, viewerRole = 'advisor', onAccept, onRegenerate, ipsVersions = [], onVersionSelect, onDelete, generatingIPS = false }: IPSEditorProps) {
  const [isEditing, setIsEditing] = useState(false);
  const [isDeleting, setIsDeleting] = useState(false);
  const [formData, setFormData] = useState({
    investment_objective: ips.investment_objective || '',
    time_horizon_years: Number(ips.time_horizon_years) || 0,
    liquidity_needs: Number(ips.liquidity_needs) || 0,
    tax_considerations: Number(ips.tax_considerations) || 0,
    rebalancing_frequency: ips.rebalancing_frequency || 'Quarterly',
    rebalancing_strategy_description: ips.rebalancing_strategy_description || '',
    monitoring_review_description: ips.monitoring_review_description || '',
    constraints_description: ips.constraints_description || '',
    goals_description: ips.goals_description || '',
    rebalancing_band_percent: Number(ips.rebalancing_band_percent) || 5,
    status: ips.status || 'Draft',
    risk_category: ips.risk_category || 'Moderate'
  });

  const handleDelete = async () => {
    if (!window.confirm('Are you sure you want to delete this draft IPS? This action cannot be undone.')) return;
    
    setIsDeleting(true);
    try {
      if (onDelete) await onDelete();
    } catch (err: any) {
      
      setError(err.message || 'Failed to delete IPS');
    } finally {
      setIsDeleting(false);
    }
  };

  const [allocations, setAllocations] = useState<TargetAllocation[]>(ips.target_allocations || []);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState(false);
  const [isGeneratingPDF, setIsGeneratingPDF] = useState(false);

  useEffect(() => {
    setFormData({
      investment_objective: ips.investment_objective || '',
      time_horizon_years: Number(ips.time_horizon_years) || 0,
      liquidity_needs: Number(ips.liquidity_needs) || 0,
      tax_considerations: Number(ips.tax_considerations) || 0,
      rebalancing_frequency: ips.rebalancing_frequency || 'Quarterly',
      rebalancing_strategy_description: ips.rebalancing_strategy_description || '',
      monitoring_review_description: ips.monitoring_review_description || '',
      constraints_description: ips.constraints_description || '',
      goals_description: ips.goals_description || '',
      rebalancing_band_percent: Number(ips.rebalancing_band_percent) || 5,
      status: ips.status || 'Draft',
      risk_category: ips.risk_category || 'Moderate'
    });
    setAllocations(ips.target_allocations || []);
  }, [ips]);

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
    const { name, value } = e.target;
    const isNumeric = ['time_horizon_years', 'liquidity_needs', 'tax_considerations', 'rebalancing_band_percent'].includes(name);
    
    setFormData(prev => ({
      ...prev,
      [name]: isNumeric ? (parseFloat(value) || 0) : value
    }));
  };

  const handleAllocationChange = (index: number, field: keyof TargetAllocation, value: string) => {
    const newAllocations = [...allocations];
    newAllocations[index] = {
      ...newAllocations[index],
      [field]: field === 'asset_class' ? value : parseFloat(value) || 0
    };
    setAllocations(newAllocations);
  };

  const handleAddAllocation = () => {
    setAllocations([
      ...allocations,
      {
        id: `new-${Date.now()}`,
        ips_id: ips.id,
        asset_class: 'New Asset Class',
        target_percent: 0,
        lower_band: 0,
        upper_band: 0
      }
    ]);
  };

  const handleRemoveAllocation = (index: number) => {
    const newAllocations = [...allocations];
    newAllocations.splice(index, 1);
    setAllocations(newAllocations);
  };

  const [inconsistencies, setInconsistencies] = useState<string[]>([]);

  const checkConsistency = () => {
    const newInconsistencies = [];
    const currentTotalTarget = allocations.reduce((sum, a) => sum + (a.target_percent || 0), 0);
    if (Math.abs(currentTotalTarget - 100) > 0.1) {
      newInconsistencies.push("Total asset allocation must be 100%.");
    }
    if (formData.time_horizon_years < 1) {
      newInconsistencies.push("Time horizon must be at least 1 year.");
    }

    // Band consistency check
    allocations.forEach(alloc => {
      if (alloc.lower_band > alloc.target_percent) {
        newInconsistencies.push(`Lower band (${alloc.lower_band}%) for ${alloc.asset_class} cannot be higher than target (${alloc.target_percent}%).`);
      }
      if (alloc.upper_band < alloc.target_percent) {
        newInconsistencies.push(`Upper band (${alloc.upper_band}%) for ${alloc.asset_class} cannot be lower than target (${alloc.target_percent}%).`);
      }
    });
    
    // Cross-module consistency checks
    if (ips.risk_assessments && formData.risk_category !== ips.risk_assessments.risk_category) {
        newInconsistencies.push(`Risk category (${formData.risk_category}) does not match risk assessment (${ips.risk_assessments.risk_category}).`);
    }
    
    if (client && formData.liquidity_needs && client.liquidity_needs && Number(formData.liquidity_needs) !== client.liquidity_needs) {
        newInconsistencies.push(`Liquidity needs ($${formData.liquidity_needs}) does not match client profile ($${client.liquidity_needs}).`);
    }

    if (client && formData.tax_considerations && client.tax_bracket && Number(formData.tax_considerations) !== client.tax_bracket) {
        newInconsistencies.push(`Tax bracket (${formData.tax_considerations}%) does not match client profile (${client.tax_bracket}%).`);
    }

    // Text-parsing consistency check for time horizon
    const rangeRegex = /(\d+)\s*[-–—]\s*(\d+)\s*year(s)?/i;
    const singleYearRegex = /(\d+)\s*year(s)?/i;
    const driftRegex = /(\d+)\s*%/;

    const foundYears: { [key: string]: number } = {};

    const checkDescription = (desc: string, fieldName: string) => {
        // Check time horizon
        const rangeMatch = desc.match(rangeRegex);
        if (rangeMatch) {
            const min = parseInt(rangeMatch[1], 10);
            const max = parseInt(rangeMatch[2], 10);
            if (formData.time_horizon_years < min || formData.time_horizon_years > max) {
                newInconsistencies.push(`Time horizon in ${fieldName} (${min}-${max} years) is inconsistent with form data (${formData.time_horizon_years} years).`);
            }
            // Store for cross-section comparison (using max as representative or just flagging if different)
            foundYears[fieldName] = max; 
        } else {
            const singleMatch = desc.match(singleYearRegex);
            if (singleMatch) {
                const yearsInText = parseInt(singleMatch[1], 10);
                if (yearsInText !== formData.time_horizon_years) {
                    newInconsistencies.push(`Time horizon in ${fieldName} (${yearsInText} years) does not match form data (${formData.time_horizon_years} years).`);
                }
                foundYears[fieldName] = yearsInText;
            }
        }

        // Check drift tolerance in rebalancing strategy
        if (fieldName === "rebalancing strategy") {
            const driftMatch = desc.match(driftRegex);
            if (driftMatch) {
                const driftInText = parseInt(driftMatch[1], 10);
                if (driftInText !== formData.rebalancing_band_percent) {
                    newInconsistencies.push(`Drift tolerance in ${fieldName} (${driftInText}%) does not match form data (${formData.rebalancing_band_percent}%).`);
                }
            }
        }
    };

    if (formData.constraints_description) checkDescription(formData.constraints_description, "constraints");
    if (formData.goals_description) checkDescription(formData.goals_description, "goals");
    if (formData.rebalancing_strategy_description) checkDescription(formData.rebalancing_strategy_description, "rebalancing strategy");

    // Cross-section comparison for time horizon
    const sections = Object.keys(foundYears);
    for (let i = 0; i < sections.length; i++) {
        for (let j = i + 1; j < sections.length; j++) {
            if (foundYears[sections[i]] !== foundYears[sections[j]]) {
                newInconsistencies.push(`Mismatch: ${sections[i]} mentions ${foundYears[sections[i]]} years, but ${sections[j]} mentions ${foundYears[sections[j]]} years. Please correct for consistency.`);
            }
        }
    }

    return newInconsistencies;
  };

  const handleSubmit = async (e: React.FormEvent, forceSave = false) => {
    e.preventDefault();
    
    if (!forceSave) {
      const newInconsistencies = checkConsistency();
      if (newInconsistencies.length > 0) {
        setInconsistencies(newInconsistencies);
        return;
      }
    }
    
    setSaving(true);
    setError(null);
    setSuccess(false);
    setInconsistencies([]);

    try {
      await onSave({
        ...formData,
        allocations
      });
      setSuccess(true);
      setIsEditing(false);
      setTimeout(() => setSuccess(false), 3000);
    } catch (err: any) {
      setError(err.message || 'Failed to save IPS');
    } finally {
      setSaving(false);
    }
  };

  const totalTarget = allocations.reduce((sum, a) => sum + (a.target_percent || 0), 0);

  // Helper for AI Badge
  const AIBadge = ({ isAllocation = false }: { isAllocation?: boolean }) => (
    <span className="group relative inline-flex items-center gap-1 px-1.5 py-0.5 rounded text-[10px] font-bold bg-blue-50 text-blue-600 border border-blue-100 uppercase tracking-wider ml-2 align-middle cursor-help">
      <BrainCircuit className="w-3 h-3" />
      AI Analysis
      <Info className="w-3 h-3 text-blue-400" />
      
      {/* Tooltip */}
      <div className="absolute left-1/2 -translate-x-1/2 bottom-full mb-2 w-64 p-3 bg-slate-800 text-white text-xs rounded-lg shadow-xl opacity-0 invisible group-hover:opacity-100 group-hover:visible transition-all z-50 pointer-events-none text-left normal-case tracking-normal font-normal">
        <p className="font-bold mb-1 text-slate-200">Data Considered for AI Generation:</p>
        <ul className="list-disc pl-4 space-y-1 text-slate-300">
          <li><span className="font-semibold text-white">Client Profile:</span> Age, Income, Net Worth, Tax Bracket</li>
          <li><span className="font-semibold text-white">Risk Assessment:</span> Willingness and Ability scores, Risk Category</li>
          <li><span className="font-semibold text-white">Financial Goals:</span> Time horizon, Liquidity needs, Investment objectives</li>
          {isAllocation && (
            <>
              <li><span className="font-semibold text-white">Market Data:</span> Historical returns, Volatility, Asset correlations</li>
              <li><span className="font-semibold text-white">Base Allocation Model:</span> Thematic model for the client's risk category</li>
            </>
          )}
          <li><span className="font-semibold text-white">Questionnaire:</span> Behavioral insights and answers</li>
        </ul>
        <div className="absolute -bottom-1 left-1/2 -translate-x-1/2 w-2 h-2 bg-slate-800 rotate-45"></div>
      </div>
    </span>
  );

  // Helper for Advisor Name
  const advisorName = ips.clients?.advisors?.full_name;

  const AdvisorSignature = () => {
    if (!advisorName) {
      return <span className="text-sm text-slate-400 italic">Loading advisor...</span>;
    }
    return (
      <p className="font-semibold text-slate-900">{advisorName}</p>
    );
  };

  const handleDownloadPDF = async () => {
    setIsGeneratingPDF(true);
    try {
      const input = document.getElementById('ips-document');
      if (!input) return;

      // Create a wrapper to isolate the clone and ensure fixed width
      const wrapper = document.createElement('div');
      wrapper.style.position = 'absolute';
      wrapper.style.left = '-9999px';
      wrapper.style.top = '0';
      wrapper.style.width = '1024px';
      wrapper.style.zIndex = '-1';
      document.body.appendChild(wrapper);

      // Clone the node
      const clone = input.cloneNode(true) as HTMLElement;
      
      // Reset styles that might interfere with full capture
      clone.style.width = '100%';
      clone.style.maxWidth = 'none';
      clone.style.height = 'auto';
      clone.style.maxHeight = 'none';
      clone.style.overflow = 'visible';
      clone.style.margin = '0';
      clone.style.transform = 'none';
      
      wrapper.appendChild(clone);

      // Wait for layout and potential font rendering
      await new Promise(resolve => setTimeout(resolve, 500));

      const dataUrl = await toPng(clone, {
        cacheBust: false, // Disable cache bust to avoid reloading resources
        backgroundColor: '#ffffff',
        width: 1024,
        height: clone.scrollHeight,
        style: {
          transform: 'scale(1)', // Force scale
        }
      });

      const pdfHeight = clone.scrollHeight;
      document.body.removeChild(wrapper);

      const pdf = new jsPDF({
        orientation: 'portrait',
        unit: 'px',
        format: [1024, pdfHeight]
      });

      pdf.addImage(dataUrl, 'PNG', 0, 0, 1024, pdfHeight);
      pdf.save(`IPS_${client.last_name}_${new Date().toISOString().split('T')[0]}.pdf`);
    } catch (err) {
      
      alert('Failed to generate PDF. Please try again.');
    } finally {
      setIsGeneratingPDF(false);
    }
  };

  if (!isEditing) {
    return (
      <div className="space-y-6 print:space-y-0">
        {/* Actions Bar */}
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between bg-white p-4 rounded-xl border border-slate-200 shadow-sm print:hidden relative z-10 gap-4">
          <div className="flex items-center gap-3 w-full sm:w-auto">
            <div className="p-2 bg-slate-100 rounded-lg shrink-0">
              <FileText className="w-5 h-5 text-slate-600" />
            </div>
            <div className="min-w-0">
              <h3 className="font-sans text-sm font-semibold text-slate-900 truncate">Investment Policy Statement</h3>
              {ipsVersions.length > 1 ? (
                <div className="flex items-center gap-2 mt-1">
                  <select
                    value={ips.id}
                    onChange={(e) => onVersionSelect && onVersionSelect(e.target.value)}
                    className="text-xs text-slate-600 bg-slate-50 border border-slate-200 rounded px-2 py-0.5 outline-none focus:ring-1 focus:ring-blue-500 max-w-[150px] sm:max-w-none"
                  >
                    {ipsVersions.map(v => (
                      <option key={v.id} value={v.id}>
                        V{v.version || 1} • {new Date(v.created_at).toLocaleDateString()}
                      </option>
                    ))}
                  </select>
                </div>
              ) : (
                <p className="text-xs text-slate-500">Version {ips.version || 1} • {new Date(ips.created_at).toLocaleDateString()}</p>
              )}
            </div>
          </div>
          <div className="flex flex-wrap items-center gap-2 sm:gap-3 w-full sm:w-auto">
            <span className={`px-2 sm:px-3 py-1 sm:py-1.5 rounded-lg text-[10px] sm:text-xs font-medium border flex items-center gap-1.5 ${
              formData.status === 'Finalized' || formData.status === 'Active'
                ? 'bg-emerald-50 text-emerald-700 border-emerald-200' 
                : 'bg-amber-50 text-amber-700 border-amber-200'
            }`}>
              {(formData.status === 'Finalized' || formData.status === 'Active') ? <ShieldCheck className="w-3.5 h-3.5" /> : null}
              {formData.status === 'Active' ? 'Active' : (formData.status === 'Finalized' ? 'Finalized' : 'Draft')}
            </span>
            <button
              type="button"
              onClick={handleDownloadPDF}
              disabled={isGeneratingPDF}
              className="flex-1 sm:flex-none flex items-center justify-center gap-2 px-3 sm:px-4 py-2 bg-white border border-slate-200 text-slate-700 rounded-lg text-xs sm:text-sm font-medium hover:bg-slate-50 transition-colors shadow-sm cursor-pointer relative z-20 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {isGeneratingPDF ? <Loader2 className="w-4 h-4 animate-spin" /> : <Download className="w-4 h-4" />}
              <span className="hidden xs:inline">{isGeneratingPDF ? 'Generating...' : 'Download PDF'}</span>
              <span className="xs:hidden">{isGeneratingPDF ? '...' : 'PDF'}</span>
            </button>
            {viewerRole === 'advisor' && onRegenerate && (formData.status === 'Draft' || formData.status === 'Active') && (
              <button
                onClick={onRegenerate}
                disabled={generatingIPS}
                className="flex-1 sm:flex-none flex items-center justify-center gap-2 px-3 sm:px-4 py-2 bg-blue-50 text-blue-700 border border-blue-200 rounded-lg text-xs sm:text-sm font-medium hover:bg-blue-100 transition-colors shadow-sm disabled:opacity-50"
              >
                {generatingIPS ? <Loader2 className="w-4 h-4 animate-spin" /> : <BrainCircuit className="w-4 h-4" />}
                <span className="hidden xs:inline">{generatingIPS ? 'Regenerating...' : 'Regenerate'}</span>
                <span className="xs:hidden">AI</span>
              </button>
            )}
            {viewerRole === 'advisor' && onAccept && ips.status === 'Finalized' && !ips.advisor_accepted_at && (
              <button
                onClick={onAccept}
                className="flex-1 sm:flex-none flex items-center justify-center gap-2 px-3 sm:px-4 py-2 bg-blue-600 text-white rounded-lg text-xs sm:text-sm font-medium hover:bg-blue-700 transition-colors shadow-sm"
              >
                <ShieldCheck className="w-4 h-4" />
                Sign
              </button>
            )}
            {viewerRole === 'client' && onAccept && ips.status === 'Finalized' && !ips.client_accepted_at && (
              <button
                onClick={onAccept}
                className="flex-1 sm:flex-none flex items-center justify-center gap-2 px-3 sm:px-4 py-2 bg-blue-600 text-white rounded-lg text-xs sm:text-sm font-medium hover:bg-blue-700 transition-colors shadow-sm"
              >
                <ShieldCheck className="w-4 h-4" />
                Accept
              </button>
            )}
            {viewerRole === 'advisor' && (formData.status === 'Draft' || formData.status === 'Finalized') && (
              <button
                onClick={() => setIsEditing(true)}
                className="flex-1 sm:flex-none flex items-center justify-center gap-2 px-3 sm:px-4 py-2 bg-slate-900 text-white rounded-lg text-xs sm:text-sm font-medium hover:bg-slate-800 transition-colors shadow-sm"
              >
                <Edit2 className="w-4 h-4" />
                Edit
              </button>
            )}
          </div>
        </div>

        {success && (
          <div className="p-4 bg-emerald-50 border border-emerald-100 rounded-xl flex items-start gap-3 text-emerald-800 animate-in fade-in slide-in-from-top-2 print:hidden">
            <Check className="w-5 h-5 shrink-0 mt-0.5" />
            <p className="text-sm font-medium">IPS updated successfully.</p>
          </div>
        )}

        {/* DOCUMENT VIEW */}
        <div id="ips-document" className="bg-white shadow-lg rounded-xl border border-slate-200 overflow-hidden max-w-5xl mx-auto print:shadow-none print:border-none print:max-w-none print:m-0 print:rounded-none">
          
          {/* Header Section */}
          <div className="p-6 sm:p-10 border-b border-slate-100 bg-slate-50/50">
            <div className="flex flex-col sm:flex-row justify-between items-start mb-8 sm:mb-10 gap-6">
              <div className="space-y-1">
                <h1 className="font-display text-2xl sm:text-3xl font-bold text-slate-900 tracking-tight">Investment Policy Statement</h1>
                <p className="text-[10px] sm:text-sm text-slate-500 font-medium uppercase tracking-widest">Confidential Client Mandate</p>
              </div>
              <div className="text-left sm:text-right space-y-2 w-full sm:w-auto">
                <div className="flex items-center gap-2 justify-start sm:justify-end">
                  <span className={`px-2 py-0.5 rounded-full text-[10px] font-bold uppercase tracking-widest border ${
                    ips.status === 'Active' ? 'bg-emerald-50 text-emerald-600 border-emerald-100' :
                    ips.status === 'Finalized' ? 'bg-blue-50 text-blue-600 border-blue-100' :
                    'bg-slate-50 text-slate-500 border-slate-200'
                  }`}>
                    {ips.status}
                  </span>
                  {ips.client_accepted_at && ips.advisor_accepted_at && (
                    <span className="flex items-center gap-1 px-2 py-0.5 bg-emerald-500 text-white rounded-full text-[10px] font-bold uppercase tracking-widest shadow-sm shadow-emerald-200">
                      <ShieldCheck className="w-3 h-3" /> Verified
                    </span>
                  )}
                </div>
                <div className="inline-flex items-center gap-2 px-3 py-1 bg-blue-50 text-blue-700 rounded-full border border-blue-100 text-[10px] font-bold uppercase tracking-wider">
                  <ShieldCheck className="w-3 h-3" /> Fiduciary Grade
                </div>
                <p className="text-[10px] text-slate-400 font-mono uppercase tracking-tighter">Ref: IPS-{ips.id.slice(0, 8).toUpperCase()}</p>
              </div>
            </div>

            <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-5 gap-4 sm:gap-8">
              <div className="space-y-1">
                <p className="text-[10px] text-slate-400 uppercase font-bold tracking-wider">Client</p>
                <p className="text-sm sm:text-base font-bold text-slate-900">{client.first_name} {client.last_name}</p>
              </div>
              <div className="space-y-1">
                <p className="text-[10px] text-slate-400 uppercase font-bold tracking-wider">Advisor</p>
                <div className="text-sm sm:text-base">
                  <AdvisorSignature />
                </div>
              </div>
              <div className="space-y-1">
                <p className="text-[10px] text-slate-400 uppercase font-bold tracking-wider">Effective Date</p>
                <p className="text-sm sm:text-base font-bold text-slate-900">
                  {new Date(ips.created_at).toLocaleDateString()}
                </p>
              </div>
              <div className="space-y-1">
                <p className="text-[10px] text-slate-400 uppercase font-bold tracking-wider">Next Review</p>
                <p className="text-sm sm:text-base font-bold text-slate-900">
                  {new Date(new Date().setFullYear(new Date().getFullYear() + 1)).toLocaleDateString()}
                </p>
              </div>
              <div className="space-y-1">
                <p className="text-[10px] text-slate-400 uppercase font-bold tracking-wider">Dependents</p>
                <p className="text-sm sm:text-base font-bold text-slate-900">
                  {client.dependents ?? '—'}
                </p>
              </div>
            </div>
          </div>

          <div className="p-6 sm:p-10 space-y-10 sm:space-y-12">
            
            {/* Section I: Purpose */}
            <section>
              <h2 className="font-display text-xl font-bold text-slate-900 uppercase tracking-wider border-b border-slate-200 pb-3 mb-6 flex items-center gap-2">
                <span className="text-slate-400">01</span> Purpose & Mandate <AIBadge />
              </h2>
              <div className="space-y-6 text-slate-700 leading-relaxed">
                <p>
                  This Investment Policy Statement (IPS) establishes the investment mandate for <strong>{client.first_name} {client.last_name}</strong>. 
                  It defines the investment objectives, risk tolerance, and constraints that will guide the management of the portfolio.
                </p>
                <div className="prose prose-ips max-w-none italic text-slate-600">
                  <ReactMarkdown>{formData.investment_objective || "To grow capital over the long term while managing risk according to the client's profile."}</ReactMarkdown>
                </div>
              </div>
            </section>

            {/* Section II: Objectives */}
            <section>
              <h2 className="font-display text-xl font-bold text-slate-900 uppercase tracking-wider border-b border-slate-200 pb-3 mb-6 flex items-center gap-2">
                <span className="text-slate-400">02</span> Investment Objectives & Goals <AIBadge />
              </h2>
              <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-6">
                <div className="bg-white p-4 rounded-lg border border-slate-200 shadow-sm">
                  <div className="flex items-center gap-2 mb-2">
                    <Target className="w-4 h-4 text-blue-600" />
                    <h3 className="font-display text-[10px] font-bold text-slate-500 uppercase tracking-wider">Risk Profile</h3>
                  </div>
                  <p className="text-lg font-bold text-slate-900">{ips.risk_category}</p>
                </div>
                <div className="bg-white p-4 rounded-lg border border-slate-200 shadow-sm">
                  <div className="flex items-center gap-2 mb-2">
                    <TrendingUp className="w-4 h-4 text-emerald-600" />
                    <h3 className="font-display text-[10px] font-bold text-slate-500 uppercase tracking-wider">Time Horizon</h3>
                  </div>
                  <p className="text-lg font-bold text-slate-900">{formData.time_horizon_years} Years</p>
                </div>
                <div className="bg-white p-4 rounded-lg border border-slate-200 shadow-sm">
                  <div className="flex items-center gap-2 mb-2">
                    <DollarSign className="w-4 h-4 text-amber-600" />
                    <h3 className="font-display text-[10px] font-bold text-slate-500 uppercase tracking-wider">Liquidity Needs</h3>
                  </div>
                  <p className="text-lg font-bold text-slate-900">${formData.liquidity_needs?.toLocaleString()}</p>
                </div>
              </div>
              
              <div className="space-y-6 text-slate-700 leading-relaxed">
                <p>
                  The portfolio is constructed with a <strong>{ips.risk_category}</strong> risk orientation. 
                  The primary goal is to achieve returns consistent with this risk profile over a <strong>{formData.time_horizon_years}-year</strong> horizon, 
                  while maintaining sufficient liquidity to meet immediate needs of <strong>${formData.liquidity_needs?.toLocaleString()}</strong>.
                </p>

                <div className="prose prose-ips max-w-none">
                  <ReactMarkdown>{formData.goals_description || ""}</ReactMarkdown>
                </div>
              </div>
            </section>

            {/* Section III: Constraints */}
            <section>
              <h2 className="font-display text-xl font-bold text-slate-900 uppercase tracking-wider border-b border-slate-200 pb-2 mb-4 flex items-center gap-2">
                <span className="text-slate-400">03</span> Constraints & Considerations <AIBadge />
              </h2>
              <div className="space-y-6">
                <div className="prose prose-ips max-w-none text-slate-600 leading-relaxed">
                  <ReactMarkdown>{formData.constraints_description || "The portfolio is managed with consideration for the client's specific liquidity needs, tax situation, and any unique circumstances or restrictions."}</ReactMarkdown>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div className="flex items-start gap-3 p-3 bg-white rounded border border-slate-100">
                    <Scale className="w-4 h-4 text-slate-400 mt-0.5" />
                    <div>
                      <h4 className="font-display text-[10px] font-bold text-slate-700 uppercase tracking-wider">Tax Considerations</h4>
                      <p className="text-sm text-slate-600">Managed for a {formData.tax_considerations}% marginal tax bracket.</p>
                    </div>
                  </div>
                  <div className="flex items-start gap-3 p-3 bg-white rounded border border-slate-100">
                    <ShieldCheck className="w-4 h-4 text-slate-400 mt-0.5" />
                    <div>
                      <h4 className="font-display text-[10px] font-bold text-slate-700 uppercase tracking-wider">Unique Circumstances</h4>
                      <p className="text-sm text-slate-600">None specified.</p>
                    </div>
                  </div>
                </div>
              </div>
            </section>

            {/* Section IV: Asset Allocation */}
            <section>
              <h2 className="font-display text-xl font-bold text-slate-900 uppercase tracking-wider border-b border-slate-200 pb-2 mb-4 flex items-center gap-2">
                <span className="text-slate-400">04</span> Target Asset Allocation <AIBadge isAllocation={true} />
              </h2>
              <div className="overflow-x-auto -mx-6 sm:mx-0 rounded-lg sm:border border-slate-200">
                <div className="min-w-[500px] p-6 sm:p-0">
                  <table className="w-full text-sm">
                    <thead className="bg-slate-100 text-slate-700 font-display text-[10px] font-bold uppercase tracking-wider border-b border-slate-200">
                      <tr>
                        <th className="px-4 py-3 text-left">Asset Class</th>
                        <th className="px-4 py-3 text-right">Target</th>
                        <th className="px-4 py-3 text-right">Lower</th>
                        <th className="px-4 py-3 text-right">Upper</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-100">
                      {allocations.map((alloc, idx) => (
                        <tr key={alloc.id || idx} className="hover:bg-slate-50">
                          <td className="px-4 py-3 font-medium text-slate-900">{alloc.asset_class}</td>
                          <td className="px-4 py-3 text-right font-mono font-bold text-slate-700">{alloc.target_percent}%</td>
                          <td className="px-4 py-3 text-right font-mono text-slate-500">{alloc.lower_band}%</td>
                          <td className="px-4 py-3 text-right font-mono text-slate-500">{alloc.upper_band}%</td>
                        </tr>
                      ))}
                      <tr className="bg-slate-50 font-semibold border-t border-slate-200">
                        <td className="px-4 py-3 text-slate-900">Total Portfolio</td>
                        <td className="px-4 py-3 text-right text-slate-900">{totalTarget.toFixed(0)}%</td>
                        <td className="px-4 py-3 text-right" colSpan={2}></td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
            </section>

            {/* Section V: Rebalancing */}
            <section>
              <h2 className="font-display text-xl font-bold text-slate-900 uppercase tracking-wider border-b border-slate-200 pb-2 mb-4 flex items-center gap-2">
                <span className="text-slate-400">05</span> Rebalancing Strategy <AIBadge />
              </h2>
              <div className="prose prose-ips max-w-none text-slate-600 leading-relaxed mb-4">
                <ReactMarkdown>{formData.rebalancing_strategy_description || "The portfolio will be monitored and rebalanced to maintain the target asset allocation. Rebalancing occurs when an asset class drifts outside its allowable range (bands) or on a scheduled basis."}</ReactMarkdown>
              </div>
              <div className="flex gap-6 text-sm">
                <div>
                  <span className="text-slate-500 font-medium">Frequency:</span>
                  <span className="ml-2 font-semibold text-slate-900">{formData.rebalancing_frequency}</span>
                </div>
                <div className="flex items-center group">
                  <span className="text-slate-500 font-medium">Drift Tolerance:</span>
                  <span className="ml-2 font-semibold text-slate-900">+/- {formData.rebalancing_band_percent || 5}% (Absolute)</span>
                  {viewerRole === 'advisor' && (
                    <button 
                      onClick={() => setIsEditing(true)}
                      className="ml-2 p-1 text-slate-400 hover:text-blue-600 opacity-0 group-hover:opacity-100 transition-all rounded hover:bg-blue-50"
                      title="Edit Drift Tolerance"
                    >
                      <Edit3 className="w-3 h-3" />
                    </button>
                  )}
                </div>
              </div>
            </section>

            {/* Section VI: Monitoring */}
            <section>
              <h2 className="font-display text-xl font-bold text-slate-900 uppercase tracking-wider border-b border-slate-200 pb-2 mb-4 flex items-center gap-2">
                <span className="text-slate-400">06</span> Monitoring & Review <AIBadge />
              </h2>
              <div className="prose prose-ips max-w-none text-slate-600 leading-relaxed">
                <ReactMarkdown>{formData.monitoring_review_description || "The advisor will review the portfolio performance and the client's circumstances at least Annually. Performance will be measured against a composite benchmark reflecting the target asset allocation."}</ReactMarkdown>
              </div>
            </section>

            {/* Signatures */}
            <section className="pt-12 mt-16 border-t border-slate-200">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-12 md:gap-16">
                {/* Client Signature */}
                <div className="space-y-4">
                  <p className="font-display text-[10px] font-bold text-slate-400 uppercase tracking-widest">Client Acknowledgement</p>
                  <div className="h-16 border-b border-slate-300 flex items-end pb-1 justify-between">
                    {ips.client_accepted_at ? (
                      <span className="font-handwriting text-2xl text-slate-800">
                        {client.first_name} {client.last_name}
                      </span>
                    ) : (
                      viewerRole === 'client' && onAccept && ips.status === 'Finalized' && (
                        <button
                          onClick={onAccept}
                          className="px-4 py-1.5 bg-blue-600 text-white text-xs font-bold uppercase tracking-wider rounded-lg hover:bg-blue-700 transition-colors mb-1 shadow-sm print:hidden"
                        >
                          Accept & Sign
                        </button>
                      )
                    )}
                    {ips.client_accepted_at ? (
                      <span className="text-[10px] font-bold text-emerald-600 bg-emerald-50 px-2 py-0.5 rounded-full border border-emerald-100 uppercase tracking-wider flex items-center gap-1 mb-1">
                        <ShieldCheck className="w-3 h-3" /> Verified
                      </span>
                    ) : (
                      <span className="text-[10px] font-bold text-slate-300 uppercase tracking-wider mb-1">Pending Signature</span>
                    )}
                  </div>
                  <div className="flex justify-between items-start">
                    <div>
                      <p className="text-sm font-bold text-slate-900">{client.first_name} {client.last_name}</p>
                      <p className="text-xs text-slate-500">Beneficiary / Account Owner</p>
                    </div>
                    {ips.client_accepted_at && (
                      <div className="text-right">
                        <p className="text-xs text-slate-900 font-medium">{new Date(ips.client_accepted_at).toLocaleDateString()}</p>
                        <p className="text-[10px] text-slate-400 uppercase tracking-wider">Date Signed</p>
                      </div>
                    )}
                  </div>
                  {ips.client_signed_at && (
                    <p className="text-[10px] font-mono text-slate-400 mt-2 bg-slate-50 p-1 rounded border border-slate-100">
                      Digital Signature Hash: {ips.id.slice(0, 8)}-{new Date(ips.client_signed_at).getTime()}
                    </p>
                  )}
                </div>

                {/* Advisor Signature */}
                <div className="space-y-4">
                  <p className="font-display text-[10px] font-bold text-slate-400 uppercase tracking-widest">Fiduciary Acceptance</p>
                  <div className="h-16 border-b border-slate-300 flex items-end pb-1 justify-between">
                    {ips.advisor_accepted_at ? (
                      <>
                        <span className="font-handwriting text-2xl text-slate-800">
                          {advisorName || 'Senior Investment Strategist'}
                        </span>
                        <span className="text-[10px] font-bold text-emerald-600 bg-emerald-50 px-2 py-0.5 rounded-full border border-emerald-100 uppercase tracking-wider flex items-center gap-1 mb-1">
                          <ShieldCheck className="w-3 h-3" /> Verified
                        </span>
                      </>
                    ) : (
                      <>
                        <span className="text-[10px] font-bold text-slate-300 uppercase tracking-wider mb-1">Pending Signature</span>
                        {viewerRole === 'advisor' && onAccept && ips.status === 'Finalized' && (
                          <button
                            onClick={onAccept}
                            className="px-4 py-1.5 bg-blue-600 text-white text-xs font-bold uppercase tracking-wider rounded-lg hover:bg-blue-700 transition-colors mb-1 shadow-sm print:hidden"
                          >
                            Sign Now
                          </button>
                        )}
                      </>
                    )}
                  </div>
                  <div className="flex justify-between items-start">
                    <div>
                      <p className="text-sm font-bold text-slate-900">Institutional Wealth Management</p>
                      <p className="text-xs text-slate-500">Fiduciary Advisor</p>
                    </div>
                    <div className="text-right">
                      <p className="text-xs text-slate-900 font-medium">
                        {ips.advisor_accepted_at 
                          ? new Date(ips.advisor_accepted_at).toLocaleDateString() 
                          : new Date(ips.created_at).toLocaleDateString()}
                      </p>
                      <p className="text-[10px] text-slate-400 uppercase tracking-wider">
                        {ips.advisor_accepted_at ? 'Date Signed' : 'Date Issued'}
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </section>

            {/* Confidentiality Notice */}
            <footer className="mt-24 pt-8 border-t border-slate-100 text-center">
              <p className="text-[10px] text-slate-400 uppercase tracking-[0.2em] leading-relaxed max-w-2xl mx-auto">
                Confidential Document — For Institutional Use Only. This Investment Policy Statement is a dynamic document and should be reviewed periodically to ensure alignment with the client's evolving financial circumstances and market conditions.
              </p>
              <p className="text-[9px] text-slate-300 mt-4 font-mono">
                Document ID: {ips.id} | Generated by AI Strategic Advisor
              </p>
            </footer>
          </div>
        </div>
      </div>
    );
  }

  return (
    <form onSubmit={handleSubmit} className="space-y-8">
      {/* Header / Status */}
      <div className="flex items-center justify-between bg-white p-4 rounded-xl border border-slate-200">
        <div>
          <h3 className="font-sans text-lg font-semibold text-slate-900">Edit IPS Draft</h3>
          <p className="text-sm text-slate-500">Make changes to the Investment Policy Statement.</p>
        </div>
        <div className="flex items-center gap-3">
          <select
            name="status"
            value={formData.status}
            onChange={handleInputChange}
            className={`px-3 py-1.5 rounded-lg text-sm font-medium border focus:ring-2 focus:ring-blue-500 outline-none ${
              formData.status === 'Finalized' 
                ? 'bg-emerald-50 text-emerald-700 border-emerald-200' 
                : 'bg-amber-50 text-amber-700 border-amber-200'
            }`}
          >
            <option value="Draft">Draft Mode</option>
            <option value="Finalized">Finalized</option>
          </select>
          <button
            type="button"
            onClick={() => setIsEditing(false)}
            className="p-2 text-slate-400 hover:text-slate-600 hover:bg-slate-200 rounded-lg transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>
      </div>

      {inconsistencies.length > 0 && (
        <div className="p-4 bg-amber-50 border border-amber-100 rounded-xl flex flex-col gap-3 text-amber-800">
          <div className="flex items-start gap-3">
            <AlertCircle className="w-5 h-5 shrink-0 mt-0.5" />
            <div>
              <p className="font-semibold">Inconsistencies found:</p>
              <ul className="list-disc pl-5 mt-1">
                {inconsistencies.map((inc, i) => <li key={i}>{inc}</li>)}
              </ul>
            </div>
          </div>
          <button
            type="button"
            onClick={(e) => handleSubmit(e as any, true)}
            className="self-end px-4 py-2 bg-amber-600 text-white text-sm font-medium rounded-lg hover:bg-amber-700 transition-colors"
          >
            Save Anyway
          </button>
        </div>
      )}

      {error && (
        <div className="p-4 bg-red-50 border border-red-100 rounded-xl flex items-start gap-3 text-red-800">
          <AlertCircle className="w-5 h-5 shrink-0 mt-0.5" />
          <p>{error}</p>
        </div>
      )}

      {/* Core Fields */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div className="md:col-span-2">
          <label className="block text-sm font-medium text-slate-700 mb-1">Investment Objective</label>
          <textarea
            name="investment_objective"
            value={formData.investment_objective}
            onChange={handleInputChange}
            rows={12}
            className="w-full px-4 py-3 border border-slate-200 rounded-xl text-sm focus:ring-2 focus:ring-blue-500 outline-none bg-white leading-relaxed"
            placeholder="Enter the investment objective..."
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-slate-700 mb-1">Risk Category</label>
          <select
            name="risk_category"
            value={formData.risk_category}
            onChange={handleInputChange}
            className="w-full px-3 py-2 border border-slate-200 rounded-lg text-sm focus:ring-2 focus:ring-blue-500 outline-none bg-white"
          >
            <option value="Conservative">Conservative</option>
            <option value="Moderate">Moderate</option>
            <option value="Aggressive">Aggressive</option>
          </select>
        </div>

        <div>
          <label className="block text-sm font-medium text-slate-700 mb-1">Time Horizon (Years)</label>
          <input
            type="number"
            name="time_horizon_years"
            value={formData.time_horizon_years}
            onChange={handleInputChange}
            className="w-full px-3 py-2 border border-slate-200 rounded-lg text-sm focus:ring-2 focus:ring-blue-500 outline-none bg-white"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-slate-700 mb-1">Liquidity Needs ($)</label>
          <input
            type="number"
            name="liquidity_needs"
            value={formData.liquidity_needs}
            onChange={handleInputChange}
            className="w-full px-3 py-2 border border-slate-200 rounded-lg text-sm focus:ring-2 focus:ring-blue-500 outline-none bg-white"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-slate-700 mb-1">Tax Bracket (%)</label>
          <input
            type="number"
            name="tax_considerations"
            value={formData.tax_considerations}
            onChange={handleInputChange}
            className="w-full px-3 py-2 border border-slate-200 rounded-lg text-sm focus:ring-2 focus:ring-blue-500 outline-none bg-white"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-slate-700 mb-1">Rebalancing Frequency</label>
          <select
            name="rebalancing_frequency"
            value={formData.rebalancing_frequency}
            onChange={handleInputChange}
            className="w-full px-3 py-2 border border-slate-200 rounded-lg text-sm focus:ring-2 focus:ring-blue-500 outline-none bg-white"
          >
            <option value="Quarterly">Quarterly</option>
            <option value="Semi-Annually">Semi-Annually</option>
            <option value="Annually">Annually</option>
          </select>
        </div>

        <div>
          <label className="block text-sm font-medium text-slate-700 mb-1">Drift Tolerance (+/- %)</label>
          <input
            type="number"
            name="rebalancing_band_percent"
            value={formData.rebalancing_band_percent}
            onChange={handleInputChange}
            className="w-full px-3 py-2 border border-slate-200 rounded-lg text-sm focus:ring-2 focus:ring-blue-500 outline-none bg-white"
          />
        </div>

        <div className="md:col-span-2">
          <label className="block text-sm font-medium text-slate-700 mb-1">Goals & Objectives Description</label>
          <textarea
            name="goals_description"
            value={formData.goals_description || ''}
            onChange={handleInputChange}
            rows={4}
            className="w-full px-4 py-3 border border-slate-200 rounded-xl text-sm focus:ring-2 focus:ring-blue-500 outline-none bg-white leading-relaxed"
            placeholder="Describe the client's specific goals and objectives..."
          />
        </div>

        <div className="md:col-span-2">
          <label className="block text-sm font-medium text-slate-700 mb-1">Constraints & Considerations Description</label>
          <textarea
            name="constraints_description"
            value={formData.constraints_description || ''}
            onChange={handleInputChange}
            rows={4}
            className="w-full px-4 py-3 border border-slate-200 rounded-xl text-sm focus:ring-2 focus:ring-blue-500 outline-none bg-white leading-relaxed"
            placeholder="Describe any constraints, tax considerations, or unique circumstances..."
          />
        </div>

        <div className="md:col-span-2">
          <label className="block text-sm font-medium text-slate-700 mb-1">Rebalancing Strategy Description</label>
          <textarea
            name="rebalancing_strategy_description"
            value={formData.rebalancing_strategy_description || ''}
            onChange={handleInputChange}
            rows={4}
            className="w-full px-4 py-3 border border-slate-200 rounded-xl text-sm focus:ring-2 focus:ring-blue-500 outline-none bg-white leading-relaxed"
            placeholder="Describe the rebalancing strategy..."
          />
        </div>

        <div className="md:col-span-2">
          <label className="block text-sm font-medium text-slate-700 mb-1">Monitoring & Review Description</label>
          <textarea
            name="monitoring_review_description"
            value={formData.monitoring_review_description || ''}
            onChange={handleInputChange}
            rows={4}
            className="w-full px-4 py-3 border border-slate-200 rounded-xl text-sm focus:ring-2 focus:ring-blue-500 outline-none bg-white leading-relaxed"
            placeholder="Describe the monitoring and review process..."
          />
        </div>
      </div>

      {/* Allocations Table */}
      <div>
        <div className="flex items-center justify-between mb-2">
          <h4 className="text-sm font-semibold text-slate-900">Target Asset Allocation</h4>
          <div className="flex items-center gap-4">
            <button
              type="button"
              onClick={handleAddAllocation}
              className="text-xs font-semibold text-blue-600 hover:text-blue-700 transition-colors"
            >
              + Add Asset Class
            </button>
            <span className={`text-xs font-mono font-medium ${Math.abs(totalTarget - 100) < 0.1 ? 'text-emerald-600' : 'text-red-500'}`}>
              Total: {totalTarget.toFixed(1)}%
            </span>
          </div>
        </div>
        <div className="border border-slate-200 rounded-xl overflow-hidden">
          <table className="w-full text-sm text-left">
            <thead className="bg-slate-50 text-xs text-slate-500 uppercase font-medium border-b border-slate-200">
              <tr>
                <th className="px-4 py-3">Asset Class</th>
                <th className="px-4 py-3 w-32">Target %</th>
                <th className="px-4 py-3 w-32">Lower Band %</th>
                <th className="px-4 py-3 w-32">Upper Band %</th>
                <th className="px-4 py-3 w-12"></th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {allocations.map((alloc, idx) => (
                <tr key={alloc.id || idx} className="bg-white">
                  <td className="px-4 py-2">
                    <input
                      type="text"
                      value={alloc.asset_class}
                      onChange={(e) => handleAllocationChange(idx, 'asset_class', e.target.value)}
                      className="w-full px-2 py-1 border border-slate-200 rounded text-sm focus:ring-1 focus:ring-blue-500 outline-none font-medium text-slate-900"
                    />
                  </td>
                  <td className="px-4 py-2">
                    <input
                      type="number"
                      value={alloc.target_percent}
                      onChange={(e) => handleAllocationChange(idx, 'target_percent', e.target.value)}
                      className="w-full px-2 py-1 border border-slate-200 rounded text-sm text-right focus:ring-1 focus:ring-blue-500 outline-none"
                    />
                  </td>
                  <td className="px-4 py-2">
                    <input
                      type="number"
                      value={alloc.lower_band}
                      onChange={(e) => handleAllocationChange(idx, 'lower_band', e.target.value)}
                      className="w-full px-2 py-1 border border-slate-200 rounded text-sm text-right focus:ring-1 focus:ring-blue-500 outline-none"
                    />
                  </td>
                  <td className="px-4 py-2">
                    <input
                      type="number"
                      value={alloc.upper_band}
                      onChange={(e) => handleAllocationChange(idx, 'upper_band', e.target.value)}
                      className="w-full px-2 py-1 border border-slate-200 rounded text-sm text-right focus:ring-1 focus:ring-blue-500 outline-none"
                    />
                  </td>
                  <td className="px-4 py-2 text-center">
                    <button
                      type="button"
                      onClick={() => handleRemoveAllocation(idx)}
                      className="text-slate-400 hover:text-red-500 transition-colors"
                    >
                      <X className="w-4 h-4" />
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Actions */}
      <div className="flex items-center justify-end gap-3 pt-4 border-t border-slate-100">
        <button
          type="button"
          onClick={() => setIsEditing(false)}
          className="px-6 py-2.5 bg-white border border-slate-200 text-slate-700 rounded-lg font-medium hover:bg-slate-50 transition-colors"
        >
          Cancel
        </button>
        <button
          type="submit"
          disabled={saving}
          className="flex items-center gap-2 px-6 py-2.5 bg-blue-600 hover:bg-blue-700 text-white rounded-lg font-medium transition-colors disabled:opacity-50 shadow-sm"
        >
          {saving ? <Loader2 className="w-4 h-4 animate-spin" /> : <Save className="w-4 h-4" />}
          Save Changes
        </button>
      </div>
    </form>
  );
}
