import React, { useState } from 'react';
import { Save, Loader2, AlertCircle, Check, Edit2, X, FileText, BrainCircuit, Calendar, User, ShieldCheck, Target, TrendingUp, DollarSign, Scale } from 'lucide-react';
import { IPSDocument, TargetAllocation, Client } from '../types';

interface IPSEditorProps {
  ips: IPSDocument & { target_allocations: TargetAllocation[] };
  client: Client;
  onSave: (updatedIps: any) => Promise<void>;
}

export default function IPSEditor({ ips, client, onSave }: IPSEditorProps) {
  const [isEditing, setIsEditing] = useState(false);
  const [formData, setFormData] = useState({
    investment_objective: ips.investment_objective,
    time_horizon_years: ips.time_horizon_years,
    liquidity_needs: ips.liquidity_needs,
    tax_considerations: ips.tax_considerations,
    rebalancing_frequency: ips.rebalancing_frequency,
    status: ips.status
  });

  const [allocations, setAllocations] = useState<TargetAllocation[]>(ips.target_allocations || []);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState(false);

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
    const { name, value } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: name === 'time_horizon_years' || name === 'liquidity_needs' || name === 'tax_considerations' 
        ? parseFloat(value) 
        : value
    }));
  };

  const handleAllocationChange = (index: number, field: keyof TargetAllocation, value: string) => {
    const newAllocations = [...allocations];
    newAllocations[index] = {
      ...newAllocations[index],
      [field]: parseFloat(value)
    };
    setAllocations(newAllocations);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setSaving(true);
    setError(null);
    setSuccess(false);

    try {
      await onSave({
        ...formData,
        allocations
      });
      setSuccess(true);
      setIsEditing(false);
      setTimeout(() => setSuccess(false), 3000);
    } catch (err: any) {
      setError(err.message || 'Failed to save IPS');
    } finally {
      setSaving(false);
    }
  };

  const totalTarget = allocations.reduce((sum, a) => sum + (a.target_percent || 0), 0);

  // Helper for AI Badge
  const AIBadge = () => (
    <span className="inline-flex items-center gap-1 px-1.5 py-0.5 rounded text-[10px] font-bold bg-blue-50 text-blue-600 border border-blue-100 uppercase tracking-wider ml-2 align-middle" title="Generated by AI">
      <BrainCircuit className="w-3 h-3" />
      AI Generated
    </span>
  );

  if (!isEditing) {
    return (
      <div className="space-y-6">
        {/* Actions Bar */}
        <div className="flex items-center justify-between bg-white p-4 rounded-xl border border-slate-200 shadow-sm">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-slate-100 rounded-lg">
              <FileText className="w-5 h-5 text-slate-600" />
            </div>
            <div>
              <h3 className="text-sm font-semibold text-slate-900">Investment Policy Statement</h3>
              <p className="text-xs text-slate-500">Version 1.0 • {new Date(ips.created_at).toLocaleDateString()}</p>
            </div>
          </div>
          <div className="flex items-center gap-3">
            <span className={`px-3 py-1.5 rounded-lg text-xs font-medium border flex items-center gap-1.5 ${
              formData.status === 'Finalized' 
                ? 'bg-emerald-50 text-emerald-700 border-emerald-200' 
                : 'bg-amber-50 text-amber-700 border-amber-200'
            }`}>
              {formData.status === 'Finalized' ? <ShieldCheck className="w-3.5 h-3.5" /> : <Edit2 className="w-3.5 h-3.5" />}
              {formData.status === 'Finalized' ? 'Active Policy' : 'Draft Mode'}
            </span>
            <button
              onClick={() => setIsEditing(true)}
              className="flex items-center gap-2 px-4 py-2 bg-slate-900 text-white rounded-lg text-sm font-medium hover:bg-slate-800 transition-colors shadow-sm"
            >
              <Edit2 className="w-4 h-4" />
              Edit Document
            </button>
          </div>
        </div>

        {success && (
          <div className="p-4 bg-emerald-50 border border-emerald-100 rounded-xl flex items-start gap-3 text-emerald-800 animate-in fade-in slide-in-from-top-2">
            <Check className="w-5 h-5 shrink-0 mt-0.5" />
            <p className="text-sm font-medium">IPS updated successfully.</p>
          </div>
        )}

        {/* DOCUMENT VIEW */}
        <div className="bg-white shadow-lg rounded-xl border border-slate-200 overflow-hidden max-w-5xl mx-auto print:shadow-none print:border-none">
          
          {/* Header Section */}
          <div className="bg-slate-50 border-b border-slate-200 p-10">
            <div className="flex justify-between items-start mb-10">
              <div>
                <h1 className="text-3xl font-serif font-bold text-slate-900 mb-2">Investment Policy Statement</h1>
                <p className="text-slate-500 text-sm uppercase tracking-widest font-medium">Confidential Client Document</p>
              </div>
              <div className="text-right">
                <div className="inline-block px-3 py-1 bg-white border border-slate-200 rounded text-xs font-mono text-slate-500">
                  REF: {ips.id.slice(0, 8).toUpperCase()}
                </div>
              </div>
            </div>

            <div className="grid grid-cols-2 md:grid-cols-4 gap-8 text-sm">
              <div>
                <p className="text-xs text-slate-400 uppercase font-bold mb-1">Prepared For</p>
                <p className="font-semibold text-slate-900 flex items-center gap-2">
                  <User className="w-3.5 h-3.5 text-slate-400" />
                  {client.first_name} {client.last_name}
                </p>
              </div>
              <div>
                <p className="text-xs text-slate-400 uppercase font-bold mb-1">Advisor</p>
                <p className="font-semibold text-slate-900">Wealth Advisor</p>
              </div>
              <div>
                <p className="text-xs text-slate-400 uppercase font-bold mb-1">Date Created</p>
                <p className="font-semibold text-slate-900 flex items-center gap-2">
                  <Calendar className="w-3.5 h-3.5 text-slate-400" />
                  {new Date(ips.created_at).toLocaleDateString()}
                </p>
              </div>
              <div>
                <p className="text-xs text-slate-400 uppercase font-bold mb-1">Review Date</p>
                <p className="font-semibold text-slate-900">
                  {new Date(new Date().setFullYear(new Date().getFullYear() + 1)).toLocaleDateString()}
                </p>
              </div>
            </div>
          </div>

          <div className="p-10 space-y-12">
            
            {/* Section I: Purpose */}
            <section>
              <h2 className="text-sm font-bold text-slate-900 uppercase tracking-wider border-b border-slate-200 pb-3 mb-6 flex items-center gap-2">
                <span className="text-slate-400">01</span> Purpose & Mandate
              </h2>
              <div className="prose prose-slate prose-sm max-w-none text-slate-600">
                <p>
                  This Investment Policy Statement (IPS) establishes the investment mandate for <strong>{client.first_name} {client.last_name}</strong>. 
                  It defines the investment objectives, risk tolerance, and constraints that will guide the management of the portfolio.
                </p>
                <div className="mt-4 p-4 bg-slate-50 rounded-lg border border-slate-100">
                  <h3 className="text-xs font-bold text-slate-500 uppercase mb-2">Primary Investment Mandate <AIBadge /></h3>
                  <p className="text-slate-800 italic leading-relaxed">
                    "{formData.investment_objective || "To grow capital over the long term while managing risk according to the client's profile."}"
                  </p>
                </div>
              </div>
            </section>

            {/* Section II: Objectives */}
            <section>
              <h2 className="text-sm font-bold text-slate-900 uppercase tracking-wider border-b border-slate-200 pb-3 mb-6 flex items-center gap-2">
                <span className="text-slate-400">02</span> Investment Objectives & Goals
              </h2>
              <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-6">
                <div className="bg-white p-4 rounded-lg border border-slate-200 shadow-sm">
                  <div className="flex items-center gap-2 mb-2">
                    <Target className="w-4 h-4 text-blue-600" />
                    <h3 className="text-xs font-bold text-slate-500 uppercase">Risk Profile</h3>
                  </div>
                  <p className="text-lg font-bold text-slate-900">{ips.risk_category}</p>
                </div>
                <div className="bg-white p-4 rounded-lg border border-slate-200 shadow-sm">
                  <div className="flex items-center gap-2 mb-2">
                    <TrendingUp className="w-4 h-4 text-emerald-600" />
                    <h3 className="text-xs font-bold text-slate-500 uppercase">Time Horizon</h3>
                  </div>
                  <p className="text-lg font-bold text-slate-900">{formData.time_horizon_years} Years</p>
                </div>
                <div className="bg-white p-4 rounded-lg border border-slate-200 shadow-sm">
                  <div className="flex items-center gap-2 mb-2">
                    <DollarSign className="w-4 h-4 text-amber-600" />
                    <h3 className="text-xs font-bold text-slate-500 uppercase">Liquidity Needs</h3>
                  </div>
                  <p className="text-lg font-bold text-slate-900">${formData.liquidity_needs?.toLocaleString()}</p>
                </div>
              </div>
              
              <div className="space-y-6">
                <p className="text-sm text-slate-600 leading-relaxed">
                  The portfolio is constructed with a <strong>{ips.risk_category}</strong> risk orientation. 
                  The primary goal is to achieve returns consistent with this risk profile over a <strong>{formData.time_horizon_years}-year</strong> horizon, 
                  while maintaining sufficient liquidity to meet immediate needs of <strong>${formData.liquidity_needs?.toLocaleString()}</strong>.
                </p>

                {ips.risk_assessments?.ai_behavior_summary && (
                  <div className="p-4 bg-blue-50/50 rounded-lg border border-blue-100">
                    <h3 className="text-xs font-bold text-slate-500 uppercase mb-2">Suitability Analysis <AIBadge /></h3>
                    <p className="text-slate-800 text-sm leading-relaxed">
                      {ips.risk_assessments.ai_behavior_summary.split('[SUITABILITY_ANALYSIS]:')[0].split('[CONFIDENCE_BREAKDOWN]:')[0].trim()}
                    </p>
                  </div>
                )}
              </div>
            </section>

            {/* Section III: Constraints */}
            <section>
              <h2 className="text-sm font-bold text-slate-900 uppercase tracking-wider border-b border-slate-200 pb-2 mb-4 flex items-center gap-2">
                <span className="text-slate-400">03</span> Constraints & Considerations
              </h2>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="flex items-start gap-3 p-3 bg-slate-50 rounded border border-slate-100">
                  <Scale className="w-4 h-4 text-slate-400 mt-0.5" />
                  <div>
                    <h4 className="text-xs font-bold text-slate-700 uppercase">Tax Considerations</h4>
                    <p className="text-sm text-slate-600">Managed for a {formData.tax_considerations}% marginal tax bracket.</p>
                  </div>
                </div>
                <div className="flex items-start gap-3 p-3 bg-slate-50 rounded border border-slate-100">
                  <ShieldCheck className="w-4 h-4 text-slate-400 mt-0.5" />
                  <div>
                    <h4 className="text-xs font-bold text-slate-700 uppercase">Unique Circumstances</h4>
                    <p className="text-sm text-slate-600">None specified.</p>
                  </div>
                </div>
              </div>
            </section>

            {/* Section IV: Asset Allocation */}
            <section>
              <h2 className="text-sm font-bold text-slate-900 uppercase tracking-wider border-b border-slate-200 pb-2 mb-4 flex items-center gap-2">
                <span className="text-slate-400">04</span> Target Asset Allocation
              </h2>
              <div className="overflow-hidden rounded-lg border border-slate-200">
                <table className="w-full text-sm">
                  <thead className="bg-slate-100 text-slate-700 font-semibold border-b border-slate-200">
                    <tr>
                      <th className="px-4 py-3 text-left">Asset Class</th>
                      <th className="px-4 py-3 text-right">Target Allocation</th>
                      <th className="px-4 py-3 text-right">Lower Band</th>
                      <th className="px-4 py-3 text-right">Upper Band</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-100">
                    {allocations.map((alloc, idx) => (
                      <tr key={alloc.id || idx} className="hover:bg-slate-50">
                        <td className="px-4 py-3 font-medium text-slate-900">{alloc.asset_class}</td>
                        <td className="px-4 py-3 text-right font-mono font-bold text-slate-700">{alloc.target_percent}%</td>
                        <td className="px-4 py-3 text-right font-mono text-slate-500">{alloc.lower_band}%</td>
                        <td className="px-4 py-3 text-right font-mono text-slate-500">{alloc.upper_band}%</td>
                      </tr>
                    ))}
                    <tr className="bg-slate-50 font-semibold border-t border-slate-200">
                      <td className="px-4 py-3 text-slate-900">Total Portfolio</td>
                      <td className="px-4 py-3 text-right text-slate-900">{totalTarget.toFixed(0)}%</td>
                      <td className="px-4 py-3 text-right" colSpan={2}></td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </section>

            {/* Section V: Rebalancing */}
            <section>
              <h2 className="text-sm font-bold text-slate-900 uppercase tracking-wider border-b border-slate-200 pb-2 mb-4 flex items-center gap-2">
                <span className="text-slate-400">05</span> Rebalancing Strategy
              </h2>
              <p className="text-sm text-slate-600 leading-relaxed mb-4">
                The portfolio will be monitored and rebalanced to maintain the target asset allocation. 
                Rebalancing occurs when an asset class drifts outside its allowable range (bands) or on a scheduled basis.
              </p>
              <div className="flex gap-6 text-sm">
                <div>
                  <span className="text-slate-500 font-medium">Frequency:</span>
                  <span className="ml-2 font-semibold text-slate-900">{formData.rebalancing_frequency}</span>
                </div>
                <div>
                  <span className="text-slate-500 font-medium">Drift Tolerance:</span>
                  <span className="ml-2 font-semibold text-slate-900">+/- 5% (Absolute)</span>
                </div>
              </div>
            </section>

            {/* Section VI: Monitoring */}
            <section>
              <h2 className="text-sm font-bold text-slate-900 uppercase tracking-wider border-b border-slate-200 pb-2 mb-4 flex items-center gap-2">
                <span className="text-slate-400">06</span> Monitoring & Review
              </h2>
              <p className="text-sm text-slate-600 leading-relaxed">
                The advisor will review the portfolio performance and the client's circumstances at least <strong>Annually</strong>. 
                Performance will be measured against a composite benchmark reflecting the target asset allocation.
              </p>
            </section>

            {/* Signatures */}
            <section className="pt-8 mt-12 border-t-2 border-slate-100">
              <div className="grid grid-cols-2 gap-12">
                <div>
                  <div className="h-16 border-b border-slate-300 mb-2"></div>
                  <p className="text-xs font-bold text-slate-500 uppercase">Client Signature</p>
                  <p className="text-sm font-medium text-slate-900">{client.first_name} {client.last_name}</p>
                </div>
                <div>
                  <div className="h-16 border-b border-slate-300 mb-2"></div>
                  <p className="text-xs font-bold text-slate-500 uppercase">Advisor Signature</p>
                  <p className="text-sm font-medium text-slate-900">Wealth Advisor</p>
                </div>
              </div>
            </section>

          </div>
        </div>
      </div>
    );
  }

  return (
    <form onSubmit={handleSubmit} className="space-y-8">
      {/* Header / Status */}
      <div className="flex items-center justify-between bg-slate-50 p-4 rounded-xl border border-slate-200">
        <div>
          <h3 className="text-lg font-semibold text-slate-900">Edit IPS Draft</h3>
          <p className="text-sm text-slate-500">Make changes to the Investment Policy Statement.</p>
        </div>
        <div className="flex items-center gap-3">
          <select
            name="status"
            value={formData.status}
            onChange={handleInputChange}
            className={`px-3 py-1.5 rounded-lg text-sm font-medium border focus:ring-2 focus:ring-blue-500 outline-none ${
              formData.status === 'Finalized' 
                ? 'bg-emerald-50 text-emerald-700 border-emerald-200' 
                : 'bg-amber-50 text-amber-700 border-amber-200'
            }`}
          >
            <option value="Draft">Draft Mode</option>
            <option value="Finalized">Finalized</option>
          </select>
          <button
            type="button"
            onClick={() => setIsEditing(false)}
            className="p-2 text-slate-400 hover:text-slate-600 hover:bg-slate-200 rounded-lg transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>
      </div>

      {error && (
        <div className="p-4 bg-red-50 border border-red-100 rounded-xl flex items-start gap-3 text-red-800">
          <AlertCircle className="w-5 h-5 shrink-0 mt-0.5" />
          <p>{error}</p>
        </div>
      )}

      {/* Core Fields */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div className="md:col-span-2">
          <label className="block text-sm font-medium text-slate-700 mb-1">Investment Objective</label>
          <textarea
            name="investment_objective"
            value={formData.investment_objective}
            onChange={handleInputChange}
            rows={12}
            className="w-full px-4 py-3 border border-slate-200 rounded-xl text-sm focus:ring-2 focus:ring-blue-500 outline-none bg-white leading-relaxed"
            placeholder="Enter the investment objective..."
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-slate-700 mb-1">Time Horizon (Years)</label>
          <input
            type="number"
            name="time_horizon_years"
            value={formData.time_horizon_years}
            onChange={handleInputChange}
            className="w-full px-3 py-2 border border-slate-200 rounded-lg text-sm focus:ring-2 focus:ring-blue-500 outline-none bg-white"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-slate-700 mb-1">Liquidity Needs ($)</label>
          <input
            type="number"
            name="liquidity_needs"
            value={formData.liquidity_needs}
            onChange={handleInputChange}
            className="w-full px-3 py-2 border border-slate-200 rounded-lg text-sm focus:ring-2 focus:ring-blue-500 outline-none bg-white"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-slate-700 mb-1">Tax Bracket (%)</label>
          <input
            type="number"
            name="tax_considerations"
            value={formData.tax_considerations}
            onChange={handleInputChange}
            className="w-full px-3 py-2 border border-slate-200 rounded-lg text-sm focus:ring-2 focus:ring-blue-500 outline-none bg-white"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-slate-700 mb-1">Rebalancing Frequency</label>
          <select
            name="rebalancing_frequency"
            value={formData.rebalancing_frequency}
            onChange={handleInputChange}
            className="w-full px-3 py-2 border border-slate-200 rounded-lg text-sm focus:ring-2 focus:ring-blue-500 outline-none bg-white"
          >
            <option value="Quarterly">Quarterly</option>
            <option value="Semi-Annually">Semi-Annually</option>
            <option value="Annually">Annually</option>
          </select>
        </div>
      </div>

      {/* Allocations Table */}
      <div>
        <div className="flex items-center justify-between mb-2">
          <h4 className="text-sm font-semibold text-slate-900">Target Asset Allocation</h4>
          <span className={`text-xs font-mono font-medium ${Math.abs(totalTarget - 100) < 0.1 ? 'text-emerald-600' : 'text-red-500'}`}>
            Total: {totalTarget.toFixed(1)}%
          </span>
        </div>
        <div className="border border-slate-200 rounded-xl overflow-hidden">
          <table className="w-full text-sm text-left">
            <thead className="bg-slate-50 text-xs text-slate-500 uppercase font-medium border-b border-slate-200">
              <tr>
                <th className="px-4 py-3">Asset Class</th>
                <th className="px-4 py-3 w-32">Target %</th>
                <th className="px-4 py-3 w-32">Lower Band %</th>
                <th className="px-4 py-3 w-32">Upper Band %</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {allocations.map((alloc, idx) => (
                <tr key={alloc.id || idx} className="bg-white">
                  <td className="px-4 py-2 font-medium text-slate-900">{alloc.asset_class}</td>
                  <td className="px-4 py-2">
                    <input
                      type="number"
                      value={alloc.target_percent}
                      onChange={(e) => handleAllocationChange(idx, 'target_percent', e.target.value)}
                      className="w-full px-2 py-1 border border-slate-200 rounded text-sm text-right focus:ring-1 focus:ring-blue-500 outline-none"
                    />
                  </td>
                  <td className="px-4 py-2">
                    <input
                      type="number"
                      value={alloc.lower_band}
                      onChange={(e) => handleAllocationChange(idx, 'lower_band', e.target.value)}
                      className="w-full px-2 py-1 border border-slate-200 rounded text-sm text-right focus:ring-1 focus:ring-blue-500 outline-none"
                    />
                  </td>
                  <td className="px-4 py-2">
                    <input
                      type="number"
                      value={alloc.upper_band}
                      onChange={(e) => handleAllocationChange(idx, 'upper_band', e.target.value)}
                      className="w-full px-2 py-1 border border-slate-200 rounded text-sm text-right focus:ring-1 focus:ring-blue-500 outline-none"
                    />
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Actions */}
      <div className="flex items-center justify-end gap-3 pt-4 border-t border-slate-100">
        <button
          type="button"
          onClick={() => setIsEditing(false)}
          className="px-6 py-2.5 bg-white border border-slate-200 text-slate-700 rounded-lg font-medium hover:bg-slate-50 transition-colors"
        >
          Cancel
        </button>
        <button
          type="submit"
          disabled={saving}
          className="flex items-center gap-2 px-6 py-2.5 bg-blue-600 hover:bg-blue-700 text-white rounded-lg font-medium transition-colors disabled:opacity-50 shadow-sm"
        >
          {saving ? <Loader2 className="w-4 h-4 animate-spin" /> : <Save className="w-4 h-4" />}
          Save Changes
        </button>
      </div>
    </form>
  );
}
